name: Dump

on:
  workflow_dispatch:
    paths-ignore:
      - '*.md'
    branches: [ main ]
    inputs:
      target_url:
        required: true
        description: 'Target URL (Required)'

jobs:
  dump:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: set-git-identity
        run: |
          git config --global user.name "${{ secrets.GIT_IDENTITY_USER_NAME}}"
          git config --global user.email "${{ secrets.GIT_IDENTITY_USER_EMAIL}}"
      - name: install-required-py3-pkgs
        run: |
          sudo python3 -m pip install wheel setuptools
      - name: clone-dumper
        run: |
          git clone -b main --depth=1 --single-branch https://github.com/DumprX/DumprX
          sudo chmod -R 777 DumprX
      - name: write-dumper-cfgs
        run: |
          cd DumprX
          echo "BaCO3Team" >> ".github_orgname"
          echo "${{ secrets.GH_TOKEN }}" >> ".github_token"
      - name: setup-dumper
        run: |
          cd DumprX
          sudo bash setup.sh
      - name: dump
        run: |
          cd DumprX
          sudo bash dumper.sh "${{ github.event.inputs.target_url }}"
